### ISSUE TITLE
Custom user-agent field results in anomalous behavior

### ISSUE THREAD

**Issue by jsf9k** [18F/domain-scan#206]
I noticed this because of an issue brought up by @Essex09.  He noticed that for the domain `webmail.usap.gov`, `pshtt` gave one result when run by itself but another when run via `domain-scan`.

The `user-agent` [specified when `pshtt` is run by `domain-scan`](https://github.com/18F/domain-scan/blob/1929ad59dd344b60ffe6f83aa34ca2db9112eca1/scanners/pshtt.py#L16) causes problems with the domain `webmail.usap.gov`.  When `curl` is run against `http://webmail.usap.gov` with any `user-agent` that starts with `github` a 503 code is returned, but otherwise a 301 code is returned.

With a `user-agent` of `github`:
```
$ curl --head --user-agent "github" http://webmail.usap.gov
HTTP/1.1 503 Service Unavailable
Content-Type: text/html; charset=UTF-8
Content-Length: 4706
Connection: close
P3P: CP="CAO PSA OUR"
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
```

With a `user-agent` of `blah`:
```
$ curl --head --user-agent "blah" http://webmail.usap.gov
HTTP/1.1 301 Moved Permanently
Content-Length: 192
Content-Type: text/html; charset=UTF-8
Location: https://webmail.usap.gov/scripts/WhlFilter.dll?pCtxt=0000000003FDB890
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Mon, 19 Mar 2018 18:10:40 GMT
```

Could we remove the custom `user-agent` string that `domain-scan` uses without any negative impact?

**Comment by konklone** [comment]
The `User-Agent` used to be overrideable in the `pshtt` scanner, but it looks like that got dropped during a refactor. (The comment still remains saying it's overrideable, but it's wrong.)

I would be up for changing the default user agent to avoid this, but I think it would also be good to allow an override so that specific entities/programs making use of domain-scan can consistently identify themselves across various tools.

I'm not aware of any downstream usage of the current user agent that would result in breakage if we made any changes.

**Comment by jsf9k** [comment]
OK, I will make the {{user-agent}} configurable again.
